version: '3.7'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    user: 1000:1000
    container_name: db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"


volumes:
  postgres_data: